// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVSqBB8DgRmwwDpvp2UCzrrn7rkmh0AQ',
    appId: '1:1046518037283:web:e163f75949708e3f1caa96',
    messagingSenderId: '1046518037283',
    projectId: 'codetool-f919a',
    authDomain: 'codetool-f919a.firebaseapp.com',
    storageBucket: 'codetool-f919a.firebasestorage.app',
    measurementId: 'G-E5QEZHXCF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMvoRBpkq3KHH40epQYK-tlgNTOOjkRQ',
    appId: '1:1046518037283:android:6f66f6f171a5d5611caa96',
    messagingSenderId: '1046518037283',
    projectId: 'codetool-f919a',
    storageBucket: 'codetool-f919a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0anXoQ7US5aHpQulOGW7HHwWOb1sGaSk',
    appId: '1:1046518037283:ios:64f56829c77e3ce51caa96',
    messagingSenderId: '1046518037283',
    projectId: 'codetool-f919a',
    storageBucket: 'codetool-f919a.firebasestorage.app',
    iosBundleId: 'com.example.codeTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0anXoQ7US5aHpQulOGW7HHwWOb1sGaSk',
    appId: '1:1046518037283:ios:64f56829c77e3ce51caa96',
    messagingSenderId: '1046518037283',
    projectId: 'codetool-f919a',
    storageBucket: 'codetool-f919a.firebasestorage.app',
    iosBundleId: 'com.example.codeTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVSqBB8DgRmwwDpvp2UCzrrn7rkmh0AQ',
    appId: '1:1046518037283:web:e7fb21f408af7d731caa96',
    messagingSenderId: '1046518037283',
    projectId: 'codetool-f919a',
    authDomain: 'codetool-f919a.firebaseapp.com',
    storageBucket: 'codetool-f919a.firebasestorage.app',
    measurementId: 'G-C29W0CSH1R',
  );
}
